const players = [
  { name: "erling haaland", team: "manchester city", position: "forward", country: "norway" },
  { name: "phil foden", team: "manchester city", position: "midfielder", country: "england" },
  { name: "kevin de bruyne", team: "manchester city", position: "midfielder", country: "belgium" },
  { name: "bukayo saka", team: "arsenal", position: "winger", country: "england" },
  { name: "declan rice", team: "arsenal", position: "midfielder", country: "england" },
  { name: "martin odegaard", team: "arsenal", position: "midfielder", country: "norway" },
  { name: "mohamed salah", team: "liverpool", position: "forward", country: "egypt" },
  { name: "virgil van dijk", team: "liverpool", position: "defender", country: "netherlands" },
  { name: "trent alexander-arnold", team: "liverpool", position: "defender", country: "england" },
  { name: "bruno fernandes", team: "manchester united", position: "midfielder", country: "portugal" },
  { name: "marcus rashford", team: "manchester united", position: "forward", country: "england" },
  { name: "casemiro", team: "manchester united", position: "midfielder", country: "brazil" },
  { name: "son heung-min", team: "tottenham hotspur", position: "forward", country: "south korea" },
  { name: "james maddison", team: "tottenham hotspur", position: "midfielder", country: "england" },
  { name: "richarlison", team: "tottenham hotspur", position: "forward", country: "brazil" },
  { name: "cole palmer", team: "chelsea", position: "forward", country: "england" },
  { name: "enzo fernandez", team: "chelsea", position: "midfielder", country: "argentina" },
  { name: "reece james", team: "chelsea", position: "defender", country: "england" },
  { name: "alexander isak", team: "newcastle united", position: "forward", country: "sweden" },
  { name: "bruno guimaraes", team: "newcastle united", position: "midfielder", country: "brazil" },
  { name: "ollie watkins", team: "aston villa", position: "forward", country: "england" },
  { name: "emiliano martinez", team: "aston villa", position: "goalkeeper", country: "argentina" },
  { name: "jarrod bowen", team: "west ham united", position: "forward", country: "england" },
  { name: "lucas paqueta", team: "west ham united", position: "midfielder", country: "brazil" },
  { name: "eberechi eze", team: "crystal palace", position: "midfielder", country: "england" },
  { name: "dominic solanke", team: "bournemouth", position: "forward", country: "england" },
  { name: "joao gomes", team: "wolverhampton wanderers", position: "midfielder", country: "brazil" },
  { name: "pascal gross", team: "brighton & hove albion", position: "midfielder", country: "germany" },
  { name: "jordan pickford", team: "everton", position: "goalkeeper", country: "england" },
  { name: "antonee robinson", team: "fulham", position: "defender", country: "united states" }
];
